"""Generate realistic mock data for KUKA KRC2 incidents (public version - no real plant data)."""
import random
from datetime import datetime, timedelta
from database import SessionLocal, Incident, init_db

OPERATORS = [
    "Operario A. García", "Operario J. Martín", "Operario P. Ruiz",
    "Operario M. López", "Operario D. Fernández", "Operario L. Torres",
    "Operario R. Navarro", "Operario S. Moreno"
]

ENGINEERS = [
    "Ing. A. Campos", "Ing. R. Molina", "Ing. C. Ortega",
    "Ing. F. Reyes", "Ing. I. Romero", "Ing. P. Vidal"
]

SHIFTS = ["mañana", "tarde", "noche"]

LINES = ["Línea 3A", "Línea 3B", "Línea 4C", "Línea 4D", "Línea 5E", "Línea 5F", "Línea 6G", "Línea 6H", "Línea 7J", "Línea 7K"]

REAL_INCIDENTS = [
    {
        "robot": "3A 50R1",
        "controller": "KRC2",
        "cell": "Celda-3A-50",
        "line": "Línea 3A",
        "error_code": "KCP_BLACK",
        "category": "pantalla",
        "title": "KCP en negro - Salvapantallas activo",
        "description": "El robot presenta la KCP completamente en negro. El robot sigue trabajando en automático pero no se puede operar manualmente. Se confirma que el salvapantallas del sistema está activo y no devuelve imagen.",
        "symptoms": "KCP sin imagen, robot continúa ciclo automático, no responde a pulsaciones de teclas.",
        "solution": "OFF/ON del armario eléctrico. Anular salvapantallas en configuración del sistema para evitar recurrencia.",
        "downtime": 15,
        "priority": "alta",
    },
    {
        "robot": "4C 80R2",
        "controller": "KRC2",
        "cell": "Celda-4C-80",
        "line": "Línea 4C",
        "error_code": "KCP_BLACK",
        "category": "pantalla",
        "title": "KCP en negro - Degradación conectores internos",
        "description": "Robot con KCP en negro. Se detecta presencia de degradación de aislante en conectores de alimentación y bus de la tarjeta INTERBUS PC. La oxidación ha provocado cortocircuito intermitente.",
        "symptoms": "KCP sin imagen, presencia visible de residuos de oxidación en conectores internos del armario.",
        "solution": "Limpieza exhaustiva de conectores afectados. Desactivar salvapantallas de Windows 95. Verificar estado de conectores de alimentación.",
        "downtime": 45,
        "priority": "alta",
    },
    {
        "robot": "5E 110R3",
        "controller": "KRC2",
        "cell": "Celda-5E-110",
        "line": "Línea 5E",
        "error_code": "KCP_BLACK",
        "category": "hardware",
        "title": "KCP en negro - PC NOK por degradación cableado",
        "description": "Robot con pantalla KCP en negro. Degradación de aislante extendida por cableado interno del armario. El PC presenta condensadores en mal estado y no recupera imagen.",
        "symptoms": "KCP completamente negro, no responde a ninguna tecla incluyendo ESC. Residuos visibles en múltiples conectores.",
        "solution": "Cambio de PC (manteniendo SSD original). Limpieza completa del armario. Configurar BIOS: UDMA a DISABLE en Primary y Secondary Master/Slave.",
        "downtime": 120,
        "priority": "crítica",
    },
    {
        "robot": "3B 40R4",
        "controller": "KRC2",
        "cell": "Celda-3B-40",
        "line": "Línea 3B",
        "error_code": "KCP_BLACK",
        "category": "hardware",
        "title": "KCP en negro - Cambio armario completo por degradación",
        "description": "Robot con fallo recurrente de KCP en negro. Múltiples intervenciones previas de limpieza no han sido efectivas. Degradación extensa en todo el armario afectando múltiples sistemas.",
        "symptoms": "Fallos recurrentes de pantalla en negro, reinicios aleatorios, pérdida de comunicación intermitente.",
        "solution": "Cambio de armario completo. Instalación de SSD con imagen de Laboratorio. Restauración desde Pendrive. Verificar tarjeta IBS.",
        "downtime": 480,
        "priority": "crítica",
    },
    {
        "robot": "6G 95R1",
        "controller": "KRC2",
        "cell": "Celda-6G-95",
        "line": "Línea 6G",
        "error_code": "PC_NOK",
        "category": "hardware",
        "title": "PC NOK - KCP congelada, luego negro, emergencia",
        "description": "Robot presenta secuencia de fallo: KCP se congela, pasa a negro y finalmente activa parada de emergencia. Condensadores del PC visiblemente hinchados.",
        "symptoms": "Secuencia: imagen congelada → pantalla negra → parada emergencia. Condensadores electrolíticos hinchados en placa base.",
        "solution": "Cambio de PC manteniendo SSD original. Verificar estado de condensadores antes de instalar nuevo PC.",
        "downtime": 90,
        "priority": "crítica",
    },
    {
        "robot": "4D 40R2",
        "controller": "KRC2",
        "cell": "Celda-4D-40",
        "line": "Línea 4D",
        "error_code": "ESC_CI_NOK",
        "category": "seguridades",
        "title": "Modo de operación desconocido - Tarjeta ESC-CI NOK",
        "description": "Robot muestra '?' en modo de operación. El llavín del KCP no reconoce la posición correcta. Tarjeta ESC-CI defectuosa impide la lectura del modo seleccionado.",
        "symptoms": "Símbolo '?' en indicador de modo de operación, imposibilidad de seleccionar T1/T2/AUT/EXT.",
        "solution": "Cambio de tarjeta ESC-CI. Verificar funcionamiento del llavín tras el cambio. Resetear cadena de seguridades.",
        "downtime": 60,
        "priority": "alta",
    },
    {
        "robot": "5F 170R1",
        "controller": "KRC2",
        "cell": "Celda-5F-170",
        "line": "Línea 5F",
        "error_code": "F12_ESC",
        "category": "seguridades",
        "title": "Modo operación erróneo - Fusible F12 ESC-CI mal insertado",
        "description": "Robot no reconoce modo de operación. Se detecta que el fusible F12 (4A) de la tarjeta ESC-CI no está correctamente insertado en su zócalo.",
        "symptoms": "Modo de operación no reconocido, robot no permite subir motores.",
        "solution": "Insertar fusible F12 (4A) correctamente en su zócalo en la tarjeta ESC-CI. Verificar modo tras reinserción.",
        "downtime": 10,
        "priority": "media",
    },
    {
        "robot": "5E 20R1",
        "controller": "KRC2",
        "cell": "Celda-5E-20",
        "line": "Línea 5E",
        "error_code": "SERVOBUS_RED",
        "category": "comunicación",
        "title": "ServoBus en rojo - Ventilador PC NOK, sobrecalentamiento",
        "description": "Robot presenta ServoBus en rojo de forma intermitente. Se detecta que el ventilador del PC no funciona correctamente provocando sobrecalentamiento y caída del bus de comunicación.",
        "symptoms": "ServoBus en rojo intermitente, PC caliente al tacto, ventilador no gira o gira muy lento.",
        "solution": "Cambio del ventilador del PC. Verificar temperaturas tras el cambio.",
        "downtime": 30,
        "priority": "alta",
    },
    {
        "robot": "7J 95R1",
        "controller": "KRC2",
        "cell": "Celda-7J-95",
        "line": "Línea 7J",
        "error_code": "KSD_NOK",
        "category": "accionamiento",
        "title": "Caída de bus - KSD Ejes 1 y 4 NOK",
        "description": "Robot presenta caída de ServoBus con pérdida de accionamientos de ejes 1 y 4. Las KSD de ambos ejes no responden correctamente al diagnóstico.",
        "symptoms": "ServoBus en rojo, ejes 1 y 4 sin tensión, error de accionamiento en LOG del controlador.",
        "solution": "Cambio de KSD de Eje 1 y KSD de Eje 4. Ajustar ejes tras el cambio con UEA (Set calibración). Sincronizar robot.",
        "downtime": 180,
        "priority": "crítica",
    },
    {
        "robot": "7K 97R1",
        "controller": "KRC2",
        "cell": "Celda-7K-97",
        "line": "Línea 7K",
        "error_code": "SYNC_ERR",
        "category": "comunicación",
        "title": "Error sincronización todos los ejes - Armario completo NOK",
        "description": "Robot presenta error de sincronización en todos los ejes. Se probaron múltiples cambios (PC, RDW) sin éxito. El problema era el armario completo.",
        "symptoms": "Error sincronización global, no resuelve con cambio de PC ni RDW.",
        "solution": "Cambio de PC → Igual. Cambio de RDW → Igual. Cambio de Armario completo → OK. El problema estaba en el cableado interno del armario.",
        "downtime": 960,
        "priority": "crítica",
    },
    {
        "robot": "6H 240R2",
        "controller": "KRC2",
        "cell": "Celda-6H-240",
        "line": "Línea 6H",
        "error_code": "RESOLVER_NOK",
        "category": "desincronismo",
        "title": "Desincronismo A4 - Cableado resolver dañado",
        "description": "Robot pierde ajuste del eje A4 de forma repetitiva. Se detecta deterioro del aislante en el cableado espiral del resolver del eje 4.",
        "symptoms": "Pérdida de ajuste eje A4 recurrente, desviaciones de posición, mensajes de fallo codificador eje 4.",
        "solution": "Cambiar cableado espiral completo o evaluar cambio de robot completo. El deterioro del aislante impide reparación parcial.",
        "downtime": 240,
        "priority": "crítica",
    },
    {
        "robot": "4D 40R3",
        "controller": "KRC2",
        "cell": "Celda-4D-40",
        "line": "Línea 4D",
        "error_code": "BAT_NOK",
        "category": "desincronismo",
        "title": "Pérdida de ejes - Pack baterías NOK",
        "description": "Robot pierde ajuste de ejes tras OFF/ON del armario. Baterías con tensión baja, no suministran corriente suficiente para mantener los resolvers durante el apagado.",
        "symptoms": "Desajuste de ejes tras apagado, tensión baterías baja en medición, circuito de carga KPS OK.",
        "solution": "Cambio de pack de baterías completo. Comprobar circuito de carga KPS. No apagar armario en 24h para alcanzar 80% de carga.",
        "downtime": 60,
        "priority": "alta",
    },
    {
        "robot": "7J 120R4",
        "controller": "KRC2",
        "cell": "Celda-7J-120",
        "line": "Línea 7J",
        "error_code": "BIOS_DEFAULT",
        "category": "desincronismo",
        "title": "Pérdida ejes - Pila CMOS placa base NOK",
        "description": "Robot muestra 'Valores BIOS por defecto cargados' al encender. La pila CR2032 de la placa base del PC está agotada, provocando reset de BIOS y posterior desajuste de ejes.",
        "symptoms": "Mensaje BIOS por defecto al arrancar, pierde configuración, pide contraseña Admin de Windows.",
        "solution": "Cambio de pila CR2032 3.3V en placa base. Parametrizar Windows para no pedir contraseña al reinicio. Reconfigurar BIOS.",
        "downtime": 30,
        "priority": "media",
    },
    {
        "robot": "3A 110R4",
        "controller": "KRC2",
        "cell": "Celda-3A-110",
        "line": "Línea 3A",
        "error_code": "FAN_E2_NOK",
        "category": "ventilación",
        "title": "Turbina E2 NOK - Ventilador trasero inferior ardiendo",
        "description": "Robot con alarma de sobretemperatura. La turbina E2 (trasera inferior del armario) está al tacto ardiendo y no ventila correctamente.",
        "symptoms": "Alarma sobretemperatura en controlador, turbina E2 caliente al tacto, ruido anómalo del ventilador.",
        "solution": "Cambio de Turbina E2 (ventilador trasero inferior del armario). Verificar temperatura tras el cambio.",
        "downtime": 45,
        "priority": "alta",
    },
    {
        "robot": "6G 10R3",
        "controller": "KRC2",
        "cell": "Celda-6G-10",
        "line": "Línea 6G",
        "error_code": "FAN_E1_NOK",
        "category": "ventilación",
        "title": "Ventilador E1 NOK + Fusible 2A fundido",
        "description": "Robot con ventilador E1 (24VDC interior armario) no funciona. Además se encuentra fusible de 2A fundido en el circuito del ventilador.",
        "symptoms": "Ventilador interior E1 parado, fusible 2A fundido, incremento de temperatura interna del armario.",
        "solution": "Sustituir Ventilador E1 (24VDC). Reponer fusible 2A fundido. Verificar que no haya cortocircuito.",
        "downtime": 30,
        "priority": "media",
    },
    {
        "robot": "4C 15R2",
        "controller": "KRC2",
        "cell": "Celda-4C-15",
        "line": "Línea 4C",
        "error_code": "A2_SIN_TENSION",
        "category": "accionamiento",
        "title": "Eje A2 sin tensión - KSD1-48A NOK",
        "description": "Robot presenta mensaje 'A2 sin tensión'. El accionamiento KSD1-48A del eje 2 no suministra potencia al motor.",
        "symptoms": "Eje A2 sin fuerza, mensaje de error 'A2 sin tensión' en KCP, robot no puede mover eje 2.",
        "solution": "Cambio de KSD1-48A del Eje 2. Sincronizar eje tras el cambio.",
        "downtime": 60,
        "priority": "alta",
    },
    {
        "robot": "5F 270R4",
        "controller": "KRC2",
        "cell": "Celda-5F-270",
        "line": "Línea 5F",
        "error_code": "CABLE_MOTOR_A2",
        "category": "accionamiento",
        "title": "Fallo cable motor A2 - Cableado espiral Eje 2 NOK",
        "description": "Robot con 'Fallo cable motor A2'. Se realizó prueba intercambiando KSD con resultado igual. Prueba directa KSD-Motor en laboratorio confirma cableado espiral NOK.",
        "symptoms": "Error cable motor A2, fallo persiste tras cambio de KSD, problema en cableado espiral.",
        "solution": "Prueba KSD intercambiada → Igual. Cableado Lab directo KSD-Motor → OK. Confirma cableado espiral Eje 2 dañado. Requiere cambio de cableado espiral.",
        "downtime": 300,
        "priority": "crítica",
    },
    {
        "robot": "6H 270R1",
        "controller": "KRC2",
        "cell": "Celda-6H-270",
        "line": "Línea 6H",
        "error_code": "TEMP_TRIP_A6",
        "category": "accionamiento",
        "title": "Sobretemperatura trip A6 - KSD 16 eje 6 NOK",
        "description": "Robot presenta disparos por sobretemperatura en eje A6 de forma repetitiva. La KSD 16 del eje 6 no regula correctamente la potencia.",
        "symptoms": "Trip por sobretemperatura eje 6, paradas repetitivas, KSD caliente.",
        "solution": "Cambio de KSD 16 del eje 6. Verificar temperaturas tras el cambio y monitorizar durante 24h.",
        "downtime": 60,
        "priority": "alta",
    },
    {
        "robot": "5E 30R1",
        "controller": "KRC2",
        "cell": "Celda-5E-30",
        "line": "Línea 5E",
        "error_code": "SSD_CORRUPT",
        "category": "software",
        "title": "KCP congelada + errores compilación - SSD datos corruptos",
        "description": "Robot con KCP congelada y errores de compilación al intentar ejecutar programas. Los datos del SSD están corruptos, posiblemente por apagado incorrecto o degradación.",
        "symptoms": "KCP congelada, errores de compilación en programas, imposibilidad de ejecutar ciclo automático.",
        "solution": "Cambio de SSD. Restaurar desde Pendrive de Planta.",
        "downtime": 90,
        "priority": "alta",
    },
    {
        "robot": "4D 100R1",
        "controller": "KRC2",
        "cell": "Celda-4D-100",
        "line": "Línea 4D",
        "error_code": "KUKACROSS_HANG",
        "category": "software",
        "title": "Se queda en KUKA CROSS al arrancar",
        "description": "Robot no completa el arranque, se queda colgado en la pantalla de KUKA CROSS sin avanzar al sistema operativo del controlador.",
        "symptoms": "Arranque incompleto, pantalla KUKA CROSS permanente, no llega a cargar el sistema.",
        "solution": "Cambio de disco. Si hay problemas con la restauración, extraer programas del disco original manualmente.",
        "downtime": 120,
        "priority": "alta",
    },
    {
        "robot": "6G 90R4",
        "controller": "KRC2",
        "cell": "Celda-6G-90",
        "line": "Línea 6G",
        "error_code": "WATCHDOG_KCP",
        "category": "comunicación",
        "title": "Error Watchdog KCP - Maleta congelada",
        "description": "Robot presenta error de Watchdog en la KCP. La maleta se congela completamente y requiere intervención manual.",
        "symptoms": "KCP congelada con error Watchdog en pantalla, robot en parada de emergencia.",
        "solution": "Cambio de maleta (KCP) completa. Revisar conexiones del cable entre maleta y armario.",
        "downtime": 45,
        "priority": "alta",
    },
    {
        "robot": "3B 50R1",
        "controller": "KRC2",
        "cell": "Celda-3B-50",
        "line": "Línea 3B",
        "error_code": "WATCHDOG_X5",
        "category": "comunicación",
        "title": "Watchdog KCP - Conector X5 tarjeta seguridad tirante",
        "description": "Robot con error watchdog intermitente. Se detecta que el conector X5 de la tarjeta de seguridad está tirante y hace mal contacto.",
        "symptoms": "Watchdog intermitente, desaparece al mover cables, conector X5 con juego.",
        "solution": "Sacar, limpiar e introducir correctamente el conector X5 en la tarjeta de seguridad.",
        "downtime": 15,
        "priority": "media",
    },
    {
        "robot": "7K 115R3",
        "controller": "KRC2",
        "cell": "Celda-7K-115",
        "line": "Línea 7K",
        "error_code": "IBS_CDIO_NOK",
        "category": "comunicación",
        "title": "Módulo IBS señales pinza sin tensión",
        "description": "Robot con módulo IBS de señales de pinza sin tensión. Se detecta conector de salida hembra del módulo IBS IP CDIO/R 24-8 dañado por arco eléctrico.",
        "symptoms": "Pinza no responde a comandos, módulo IBS sin tensión, conector hembra visiblemente dañado.",
        "solution": "Cambiar módulo IBS IP CDIO/R 24-8. Verificar cableado hacia pinza.",
        "downtime": 60,
        "priority": "alta",
    },
    {
        "robot": "5F 110R3",
        "controller": "KRC2",
        "cell": "Celda-5F-110",
        "line": "Línea 5F",
        "error_code": "IBUS_ON_0",
        "category": "software",
        "title": "Robot no abre pinza neumática - Variable bus desactivada",
        "description": "Robot no abre la pinza neumática. Se detecta que la variable de activación del InterBus tiene valor 0, desactivando completamente el bus.",
        "symptoms": "Pinza neumática no abre ni cierra, robot ejecuta programa pero sin actuación de herramienta.",
        "solution": "Setear variable de bus al valor correcto (1536). Verificar funcionamiento de pinza.",
        "downtime": 5,
        "priority": "media",
    },
    {
        "robot": "7J 160R1",
        "controller": "KRC2",
        "cell": "Celda-7J-160",
        "line": "Línea 7J",
        "error_code": "KPS_CARGA",
        "category": "alimentación",
        "title": "Tiempo conexión Resistencia Carga PM1 muy largo",
        "description": "Robot presenta error 'Tiempo de conexión Resistencia de Carga PM1 muy largo'. La KPS no alimenta correctamente.",
        "symptoms": "Error de tiempo de carga en pantalla, robot no sube motores, KPS sin salida.",
        "solution": "Cambio de KPS. Verificar tensiones de salida tras el cambio.",
        "downtime": 120,
        "priority": "crítica",
    },
    {
        "robot": "7K 102R1",
        "controller": "KRC2",
        "cell": "Celda-7K-102",
        "line": "Línea 7K",
        "error_code": "KPS_RELE",
        "category": "alimentación",
        "title": "No sube motores - Relés internos KPS no entran",
        "description": "Robot no sube motores. Se detecta que los relés internos de la KPS no activan, no suministrando potencia a los accionamientos.",
        "symptoms": "Robot no sube motores, sin mensaje de error claro, relés KPS no se escuchan activar.",
        "solution": "Cambio de KPS. Verificar que relés internos activan correctamente. Comprobar circuito de carga de baterías.",
        "downtime": 90,
        "priority": "alta",
    },
    {
        "robot": "5F 170R2",
        "controller": "KRC2",
        "cell": "Celda-5F-170",
        "line": "Línea 5F",
        "error_code": "INETINFO_ERR",
        "category": "software",
        "title": "InetInfo ha causado un fallo en el sistema",
        "description": "Robot muestra error 'InetInfo ha causado un fallo en el sistema'. El servicio de red de Windows 95 interfiere con el funcionamiento del controlador.",
        "symptoms": "Mensaje de error InetInfo en pantalla, robot se detiene.",
        "solution": "Confirmar el fallo en pantalla. Desconectar adaptador de red (MFC Network Adapter) para eliminar conflicto.",
        "downtime": 10,
        "priority": "baja",
    },
    {
        "robot": "6G 40R2",
        "controller": "KRC2",
        "cell": "Celda-6G-40",
        "line": "Línea 6G",
        "error_code": "PROT_OP_EXT",
        "category": "seguridades",
        "title": "Fallo Protección del Operador al pasar a EXT",
        "description": "Robot genera error de 'Protección del Operador' al intentar pasar a modo EXT (automático externo). La cadena de contactores externa no valida correctamente.",
        "symptoms": "Error protección operador solo al pasar a EXT, funciona en T1 y T2.",
        "solution": "Cambiar contactor de cadena de seguridades. La cadena de contactores externa no cerraba correctamente.",
        "downtime": 45,
        "priority": "alta",
    },
    {
        "robot": "7K 115R4",
        "controller": "KRC2",
        "cell": "Celda-7K-115",
        "line": "Línea 7K",
        "error_code": "PC_RESTART_DOOR",
        "category": "hardware",
        "title": "PC se reinicia al abrir/mover puerta armario",
        "description": "El PC se reinicia cada vez que se abre o mueve la puerta del armario. Las conexiones internas del armario están deterioradas y el movimiento provoca microcortes.",
        "symptoms": "Reinicio del PC al manipular puerta del armario, conexiones internas con juego.",
        "solution": "Cambio de armario completo (manteniendo SSD). Las conexiones internas estaban tan deterioradas que no admitían reparación parcial.",
        "downtime": 480,
        "priority": "crítica",
    },
    {
        "robot": "3A 10R1",
        "controller": "KRC2",
        "cell": "Celda-3A-10",
        "line": "Línea 3A",
        "error_code": "RAM_LOOSE",
        "category": "hardware",
        "title": "PC se reinicia - Memoria RAM suelta",
        "description": "Robot presenta reinicios del PC al abrir la puerta del armario. Se detecta que el módulo de memoria RAM está suelto en su zócalo por vibraciones.",
        "symptoms": "Reinicios aleatorios, especialmente al abrir puerta o golpes en el armario.",
        "solution": "Limpiar y recolocar correctamente la memoria RAM en su zócalo. Asegurar fijación.",
        "downtime": 15,
        "priority": "media",
    },
    {
        "robot": "4C 22R1",
        "controller": "KRC2",
        "cell": "Celda-4C-22",
        "line": "Línea 4C",
        "error_code": "X30_HARTING",
        "category": "eléctrica",
        "title": "Pines conector potencia quemados - Ejes 1,2,3 afectados",
        "description": "Robot con pines quemados en conector de potencia base robot. Afecta a ejes 1, 2 y 3. La sujeción metálica interior del conector está NOK.",
        "symptoms": "Fallos intermitentes en ejes 1, 2 y 3. Pines visiblemente quemados.",
        "solution": "Sanear conector completo (macho y hembra). Reparar sujeción metálica interior.",
        "downtime": 180,
        "priority": "crítica",
    },
    {
        "robot": "3B 40R4",
        "controller": "KRC2",
        "cell": "Celda-3B-40",
        "line": "Línea 3B",
        "error_code": "KCP_CABLE_NOK",
        "category": "pantalla",
        "title": "KCP negro esporádico - Cable prolongador NOK",
        "description": "Robot con KCP que se pone en negro de forma esporádica. Se sospecha del cable prolongador de la maleta que puede causar pérdida de señal intermitente.",
        "symptoms": "KCP negro de forma intermitente, sin patrón claro, robot sigue en automático.",
        "solution": "Conectar KCP directamente al armario para descartar prolongador. Confirmar que el problema desaparece. Quitar alargadera definitivamente.",
        "downtime": 10,
        "priority": "baja",
    },
    {
        "robot": "6H 270R2",
        "controller": "KRC2",
        "cell": "Celda-6H-270",
        "line": "Línea 6H",
        "error_code": "KPS_PM1_TENSION",
        "category": "alimentación",
        "title": "Tensión carga KPS en defecto - Oxidación + frenos",
        "description": "Robot presenta 'Tensión carga KPS PM1 en defecto'. Se activan frenos inesperadamente y pierde sincronismo. Oxidación detectada en conectores de la KPS.",
        "symptoms": "Activación inesperada de frenos, desincronismo, mensaje KPS tensión en defecto.",
        "solution": "Cambio de KPS. Limpieza exhaustiva de conectores afectados. Verificar circuito de carga y cambiar baterías.",
        "downtime": 120,
        "priority": "crítica",
    },
    {
        "robot": "7J 95R2",
        "controller": "KRC2",
        "cell": "Celda-7J-95",
        "line": "Línea 7J",
        "error_code": "ENCODER_ALL_DSE",
        "category": "accionamiento",
        "title": "Fallo cable codificador todos los ejes - Resuelto con reinicio drives",
        "description": "Robot presenta 'Confirmar cable codificador de todos los ejes'. Antes de cambiar hardware, se ejecuta reinicio de drives que elimina los fallos de codificador.",
        "symptoms": "Error cable codificador en todos los ejes, ServoBus no sube.",
        "solution": "Ejecutar reinicio de drives (DSE). El bus sube correctamente. Sincronizar robot tras la operación. No fue necesario cambio de hardware.",
        "downtime": 20,
        "priority": "media",
    },
    {
        "robot": "5E 150R1",
        "controller": "KRC2",
        "cell": "Celda-5E-150",
        "line": "Línea 5E",
        "error_code": "DCP_FAULT",
        "category": "software",
        "title": "Fallo DCP - PC/disco problemático",
        "description": "Robot muestra 'fallo DCP' de forma recurrente. Generalmente asociado a problemas de PC o disco duro degradado.",
        "symptoms": "Mensaje fallo DCP, paradas intermitentes, reinicio resuelve temporalmente.",
        "solution": "Cambio de armario completo. Instalación SSD con imagen de Laboratorio. Restaurar. Limpieza de ficheros corruptos.",
        "downtime": 480,
        "priority": "crítica",
    },
    {
        "robot": "3A 40R1",
        "controller": "KRC2",
        "cell": "Celda-3A-40",
        "line": "Línea 3A",
        "error_code": "BSOD",
        "category": "software",
        "title": "Pantallazo azul - Múltiples causas",
        "description": "Robot con pantallazo azul (BSOD) recurrente. Múltiples causas identificadas: degradación conectores, regleta de alimentación PC degradada, disco duro con sectores dañados.",
        "symptoms": "Pantalla azul de Windows 95 (BSOD), reinicios frecuentes, arranques fallidos.",
        "solution": "Limpiar conectores. Cambiar regleta alimentación PC. Clonar HDD de robot gemelo. BIOS: forzar PIO 0-4, deshabilitar UDMA. Restaurar Backup.",
        "downtime": 240,
        "priority": "crítica",
    },
    {
        "robot": "6H 250R2",
        "controller": "KRC2",
        "cell": "Celda-6H-250",
        "line": "Línea 6H",
        "error_code": "X19_NOK",
        "category": "eléctrica",
        "title": "Paro emergencia - Conector KCP base armario roto",
        "description": "Robot entra en paro de emergencia por fallo en conector de conexión KCP en base del armario. El conector está roto por esfuerzo mecánico.",
        "symptoms": "Paro de emergencia sin causa aparente, conector con daño mecánico visible.",
        "solution": "Reparar/sustituir conector en base del armario. Revisar ruta del cable para evitar esfuerzos mecánicos.",
        "downtime": 60,
        "priority": "alta",
    },
    {
        "robot": "5E 160R1",
        "controller": "KRC2",
        "cell": "Celda-5E-160",
        "line": "Línea 5E",
        "error_code": "MULTI_FAULT",
        "category": "hardware",
        "title": "Múltiples problemas tras cambio disco - Reconstrucción completa",
        "description": "Robot presenta múltiples fallos encadenados tras un cambio de disco. Requiere intervención integral: cambio de PC, SSD, restauración, calibración y sincronización completa.",
        "symptoms": "Fallos múltiples encadenados, robot no arranca correctamente tras cambio de disco.",
        "solution": "Cambiar PC. Cambiar SSD con imagen Lab. Restaurar programas. Setear fichero de calibración. Cambiar baterías. Sincronizar todos los ejes.",
        "downtime": 360,
        "priority": "crítica",
    },
    {
        "robot": "7J 140R1",
        "controller": "KRC2",
        "cell": "Celda-7J-140",
        "line": "Línea 7J",
        "error_code": "RDW_TEMP_ALL",
        "category": "accionamiento",
        "title": "Fallo codificador y temperatura todos los ejes - Cambio RDW + KSD",
        "description": "Robot con fallos de codificador y sobretemperatura en todos los ejes. Problema generalizado en la tarjeta RDW y todos los módulos KSD.",
        "symptoms": "Error codificador y temperatura en todos los ejes simultáneamente.",
        "solution": "Cambio de RDW completa. Cambio de todos los KSD. Sincronizar todos los ejes tras el cambio.",
        "downtime": 480,
        "priority": "crítica",
    },
    {
        "robot": "4C 21R3",
        "controller": "KRC2",
        "cell": "Celda-4C-21",
        "line": "Línea 4C",
        "error_code": "AUT_HANG",
        "category": "software",
        "title": "Robot parado en automático sin fallo - Espera en RUN",
        "description": "Robot se queda parado en automático sin mostrar ningún fallo en KCP. El sistema muestra 'Espera robot en RUN'. Problema intermitente sin causa clara.",
        "symptoms": "Robot detenido en automático, KCP sin error, sistema muestra espera en RUN.",
        "solution": "Solución temporal: cambiar modo de operación varias veces hasta que el robot reacciona y continúa ciclo. Problema intermitente pendiente de investigación.",
        "downtime": 5,
        "priority": "baja",
    },
    {
        "robot": "7K 120R2",
        "controller": "KRC2",
        "cell": "Celda-7K-120",
        "line": "Línea 7K",
        "error_code": "HW_INF_ERR",
        "category": "desincronismo",
        "title": "Fichero sistema no encontrado + reinicio pierde ejes",
        "description": "Robot presenta error de fichero de sistema no encontrado. Al hacer reinicio en frío se eliminan fallos pero el robot pierde ajuste de ejes. Pack baterías sin cambiar desde hace años.",
        "symptoms": "Error fichero sistema, desajuste tras reinicio, baterías antiguas.",
        "solution": "Pack baterías NOK. Cambio de baterías. NO apagar armario en 24h para que nuevas baterías alcancen 80% de carga útil.",
        "downtime": 90,
        "priority": "alta",
    },
    {
        "robot": "7J 140R2",
        "controller": "KRC2",
        "cell": "Celda-7J-140",
        "line": "Línea 7J",
        "error_code": "ENCODER_ALL",
        "category": "alimentación",
        "title": "Fallo codificador todos los ejes - KPS + oxidación conectores",
        "description": "Robot presenta fallo de codificador en todos los ejes. Se detecta oxidación en conectores de la KPS. NOTA: robot con 7º eje (carril), NO intercambiable con armario estándar de 6 ejes.",
        "symptoms": "Error codificador en todos los ejes simultáneamente, oxidación visible en conectores KPS.",
        "solution": "Cambio de KPS. Limpieza exhaustiva de conectores. NOTA: armario especial con KSD de 7º eje, no se puede sustituir con armario estándar.",
        "downtime": 150,
        "priority": "crítica",
    },
]


STATUSES_WEIGHTS = [("cerrada", 0.6), ("abierta", 0.2), ("en_progreso", 0.2)]
RESULTS = ["resuelto", "resuelto", "resuelto", "parcial", "pendiente"]


def weighted_choice(choices):
    items, weights = zip(*choices)
    return random.choices(items, weights=weights, k=1)[0]


def generate_mock_data(count: int = 50):
    init_db()
    db = SessionLocal()
    db.query(Incident).delete()
    db.commit()

    now = datetime.now()

    for i, inc_data in enumerate(REAL_INCIDENTS):
        days_ago = random.randint(0, 90)
        hours = random.randint(0, 23)
        minutes = random.randint(0, 59)
        created = now - timedelta(days=days_ago, hours=hours, minutes=minutes)

        status = weighted_choice(STATUSES_WEIGHTS)
        result = random.choice(RESULTS) if status == "cerrada" else None
        downtime = inc_data["downtime"] if status != "abierta" else None

        incident = Incident(
            created_at=created,
            updated_at=created + timedelta(minutes=random.randint(10, 480)),
            operator=random.choice(OPERATORS),
            engineer=random.choice(ENGINEERS),
            shift=random.choice(SHIFTS),
            robot_type=inc_data["robot"],
            controller=inc_data["controller"],
            cell=inc_data["cell"],
            line=inc_data["line"],
            error_code=inc_data["error_code"],
            category=inc_data["category"],
            priority=inc_data["priority"],
            status=status,
            title=inc_data["title"],
            description=inc_data["description"],
            symptoms=inc_data["symptoms"],
            solution=inc_data["solution"] if status != "abierta" else None,
            steps=None,
            downtime_min=downtime,
            result=result,
            notes=random.choice([
                None,
                "Revisar en próximo mantenimiento preventivo",
                "Solicitar repuesto a almacén",
                "Informar a turno siguiente",
                "Pendiente de validación por calidad",
                "Verificar estado en 48h",
                "Programar revisión conectores en robots adyacentes",
                "Actualizar backup tras intervención",
            ]),
            images=None,
        )
        db.add(incident)

    db.commit()
    db.close()
    print(f"Generated {len(REAL_INCIDENTS)} mock incidents.")


if __name__ == "__main__":
    generate_mock_data()
